version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my_network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    external: true
